### ISSUE TITLE
Way to exclude resource by name pattern

### ISSUE THREAD

**Issue by sstarcher** [bakito/kubexporter#269]
When helm is using a secret driver does kubexport have any way to exclude it without excluding all secrets?

Currently I'm simply doing 
```
 rm -rf **/Secret.sh.helm.release*
```

**Comment by bakito** [comment]
Hi @sstarcher 

Have you tried with the Secret's type?

```
# allows to exclude single instances with certain field values
kindByField:
    Service:
      - field: [ metadata, name ]
        # the value is compared to the string representation of the actual kind value
        values: [ exclude-me-1, exclude-me-2 ]
```
