### ISSUE TITLE
Add field filter option to include

### ISSUE THREAD

**Issue by pstefka** [bakito/kubexporter#293]
Kindly asking to add kindByField to included config option. This cloud be used to include only resources matching a field filter, e.g. having a set label, something in the line of:

```yaml
included:
  kindByField:
    *:
      - field: [ metadata.label.component ]
        values: [ 'controller' ]
```

Seems like a catch all option of "*" available for kindByField, and field nesting might be required for this to work.. Could I help somehow?

**Comment by bakito** [comment]
@pstefka Thank you for your request.
Field nesting is supported by the current exclude logic as used in exclude.kindByField
```
  kindByField:
    Service:
      - field: [ metadata, name ]
        # the value is compared to the string representation of the actual kind value
        values: [ exclude-me-1, exclude-me-2 ]
```
I'm not quite sure on how it should be implemented, as the intended default behavior is only to work with excludes.
When adding include functionality, how should this be handled?

- what has priority include or exclude?
- should exclude and include be used together?
